language: bash
services: docker

env:
  - VARIANT=apache
  - VARIANT=fpm

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VARIANT"
  - image="postfixadmin:${VARIANT}"

script:
  - travis_retry docker build -t "$image" "${VARIANT}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
